language: android
os: linux
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
addons:
  apt_packages:
    - pandoc
before_install:
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "ndk;20.1.5948944"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "cmake;3.10.2.4988404"
before_script:
  - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
  - export NDK_PATH=$ANDROID_NDK_ROOT
  - export FFMPEG_EXT_PATH="$(pwd)/extensions/ffmpeg/src/main/jni"
  - export HOST_PLATFORM="linux-x86_64"
  - export ENABLED_DECODERS=(mp3 vorbis opus flac)

script:
  - source .ci_tools/build_ffmpeg.sh

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew :extension-ffmpeg:clean :extension-ffmpeg:assembleRelease :extension-ffmpeg:bintrayUpload -PdryRun=false --debug
  on:
    branch: ffmpeg_build