language: android
os: linux
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3

android:
  components:
    # Base components
    - tools # to get the new `repository-11.xml`
    - tools # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION # get the build tools version to build the project

    # used sdk versions
    - android-$ANDROID_API_LEVEL # get the android sdk version to build the project

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - echo $ANDROID_TARGET
  - touch $HOME/.android/repositories.cfg

install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "ndk;20.1.5948944"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "cmake;3.10.2.4988404"

before_script:
  - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
  - export NDK_PATH=$ANDROID_NDK_ROOT
  - export FFMPEG_EXT_PATH="$(pwd)/extensions/ffmpeg/src/main/jni"
  - export HOST_PLATFORM="linux-x86_64"
  - export ENABLED_DECODERS=(mp3)

script:
  - source .ci_tools/build_ffmpeg.sh

deploy:
  provider: script
  skip_cleanup: true
  cleanup: false
  script: ./gradlew :extension-ffmpeg:clean :extension-ffmpeg:assembleRelease :extension-ffmpeg:bintrayUpload -PdryRun=false
  on:
    branch: ffmpeg_build